<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.paymentgateway</groupId>
    <artifactId>payment-gateway</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>api-gateway</artifactId>
  <packaging>jar</packaging>
  <name>API Gateway</name>

  <dependencies>

    <dependency>
      <groupId>com.paymentgateway</groupId>
      <artifactId>common</artifactId>
    </dependency>

    <!--
        Spring Cloud Gateway — the routing engine.
        WHY NOT spring-boot-starter-web?
        Gateway is built on WebFlux (reactive) — it cannot
        coexist with spring-boot-starter-web (servlet-based).
        Always use spring-cloud-starter-gateway.
    -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-gateway</artifactId>
    </dependency>

    <!--
        Spring Data Redis Reactive — for rate limiting.
        Gateway uses Redis to store request counts per merchant.
        WHY Redis and not in-memory?
        If you have 3 Gateway instances, in-memory counters
        are per-instance. Redis is shared across all instances —
        the rate limit is enforced cluster-wide.
    -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-redis-reactive</artifactId>
    </dependency>

    <!--
        JWT validation — parse and verify JWT tokens.
        JJWT is the most widely used Java JWT library.
    -->
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-api</artifactId>
      <version>0.12.3</version>
    </dependency>
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-impl</artifactId>
      <version>0.12.3</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-jackson</artifactId>
      <version>0.12.3</version>
      <scope>runtime</scope>
    </dependency>

    <!-- Actuator -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

</project>